---
title: "ProjectData311"
author: "Pardeep"
date: "March 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
P:\Term4\DATA311\Project\imdb-data-from-2006-to-2016\OriginalDS
```{r}
#movies <- read.csv(file = "P:/Term4/DATA311/Project/imdb-data-from-2006-to-2016/IMDB-Movie-Data.csv")
movies <- read.csv(file = "P:/Term4/DATA311/Project/imdb-data-from-2006-to-2016/OriginalDS/IMDB-Movie-Data.csv")
attach(movies)
slr <- lm(Rank ~ Revenue..Millions.) 
summary(slr)
```

## Splitting genre
```{r}
View(movies[,3])

```



```{r, eval=FALSE}
library(MASS)
movies <- read.csv(file = "P:/Term4/DATA311/Project/imdb-data-from-2006-to-2016/OriginalDS/IMDB-Movie-Data.csv")
#attach(movies)
#View(movies)
mylda <- lda(Rating ~ Revenue..Millions.+Runtime..Minutes. + Metascore ,data=movies)
table(movies$Rating, predict(mylda)$class)
#mylda
```


##Classification tree
```{r}
library(tree)
library(gclus)
movies <- read.csv(file = "P:/Term4/DATA311/Project/imdb-data-from-2006-to-2016/IMDB-Movie-Data.csv")
#attach(movies)
data(movies)
set.seed(12412)
movies$Genre <- factor(movies$Genre)
bod <- data.frame(movies)
bocl <- tree(Genre~ Rank+Runtime..Minutes.+Rating+Votes+Revenue..Millions.+Metascore , data=bod)
plot(bocl)
text(bocl)
```

##Pruning
```{r}
cv.bocl <- cv.tree(bocl, FUN = prune.misclass)
plot(cv.bocl, type="b")
```

## Minimum is at 8
```{r}
p.bocl <- prune.misclass(bocl, best=8)
plot(p.bocl)
text(p.bocl)
summary(p.bocl)
```
